# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer <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>"\
        -H "X-GitHub-Api-Version: 2022-11-28" \
         https://api.github.com/repos/AlekhyaKA/APIPOC/contributors
